In [22]:
import pandas as pd

In [30]:
df = pd.read_csv('hh.csv', sep=';')

In [31]:
df

,name,link,salary_min,salary_max,salary_currency
0,Python Developer (World of Tanks),https://spb.hh.ru/vacancy/47146423?from=vacanc...,NaN,NaN,NaN
1,Python Developer (New game product),https://spb.hh.ru/vacancy/49866239?from=vacanc...,NaN,NaN,NaN
2,Python Developer (World of Tanks),https://spb.hh.ru/vacancy/47146424?from=vacanc...,NaN,NaN,NaN
3,Python Developer (Infrastructure Projects),https://spb.hh.ru/vacancy/50491842?from=vacanc...,NaN,NaN,NaN
4,Python разработчик,https://spb.hh.ru/vacancy/49567654?from=vacanc...,NaN,NaN,NaN
...,...,...,...,...,...
775,Data Engineer,https://spb.hh.ru/vacancy/50588405?from=vacanc...,NaN,NaN,NaN
776,QA Engineer (Python),https://spb.hh.ru/vacancy/49621190?from=vacanc...,NaN,NaN,NaN
777,Разработчик Python,https://spb.hh.ru/vacancy/50413820?from=vacanc...,NaN,NaN,NaN
778,Data Scientist (Computer Vision),https://spb.hh.ru/vacancy/50272517?from=vacanc...,2500.0,4000.0,USD
779,Middle Python разработчик,https://spb.hh.ru/vacancy/50441416?from=vacanc...,NaN,NaN,NaN

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             780 non-null    object
 1   link             780 non-null    object
 2   salary_min       620 non-null    float64
 3   salary_max       355 non-null    float64
 4   salary_currency  646 non-null    object
dtypes: float64(2), object(3)
memory usage: 30.6+ KB